# Generated by Django 3.2.13 on 2022-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name", 
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Ator"
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        max_length=10, 
                        verbose_name="Data de Nascimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Elenco",
                "verbose_name_plural": "Elenco",
            },
        ),
        migrations.CreateModel(
            name="Directors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name", 
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Ator"
                    )
                ),
                (
                    "birthday",
                    models.CharField(
                        max_length=10, 
                        verbose_name="Data de Nascimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Diretor",
                "verbose_name_plural": "Diretores",
            },
        ),
        migrations.CreateModel(
            name="MainActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Papel/Novela"
                    ),
                ),
                (
                    "name", 
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Ator"
                        )
                    ),
                (
                    "birthday",
                    models.CharField(
                        max_length=10, 
                        verbose_name="Data de Nascimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ator Principal",
                "verbose_name_plural": "Ator Principal",
            },
        ),
        migrations.CreateModel(
            name="Screenwriters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name", models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Ator"
                    )
                ),
                (
                    "birthday",
                    models.CharField(
                        max_length=10, 
                        verbose_name="Data de Nascimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Roterista",
                "verbose_name_plural": "Roteristas",
            },
        ),
        migrations.CreateModel(
            name="Villains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Papel/Novela"
                    ),
                ),
                (
                    "name", 
                    models.CharField(
                        max_length=256, 
                        verbose_name="Nome do Ator"
                    )
                ),
                (
                    "birthday",
                    models.CharField(
                        max_length=10, 
                        verbose_name="Data de Nascimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vilão",
                "verbose_name_plural": "Vilões",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256, 
                        verbose_name="Título do Filme"
                    ),
                ),
                (
                    "published_year",
                    models.CharField(
                        max_length=4, 
                        verbose_name="Ano de Lançamento"
                    ),
                ),
                (
                    "synopsis", models.TextField(
                        verbose_name="Sinopse do Filme"
                    ),
                ),
                (
                    "imdb_evaluation",
                    models.CharField(
                        max_length=6, 
                        verbose_name="Avaliação do IMDB"
                    ),
                ),
                (
                    "casts",
                    models.ManyToManyField(
                        related_name="movie_casts", 
                        to="movies.Casts"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movie_directors", 
                        to="movies.Directors"
                    ),
                ),
                (
                    "main_actor",
                    models.ManyToManyField(
                        related_name="batman", 
                        to="movies.MainActor"
                    ),
                ),
                (
                    "screenwriters",
                    models.ManyToManyField(
                        related_name="movie_screenwriters", 
                        to="movies.Screenwriters"
                    ),
                ),
                (
                    "villains",
                    models.ManyToManyField(
                        related_name="movie_villains", 
                        to="movies.Villains"
                    ),
                ),
            ],
            options={
                "verbose_name": "Filme",
                "verbose_name_plural": "Filmes",
            },
        ),
    ]
