# Generated by Django 3.2.13 on 2022-05-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("birthday", models.CharField(max_length=16)),
                (
                    "demise",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("height", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name": "Cast",
                "verbose_name_plural": "Casts",
            },
        ),
        migrations.CreateModel(
            name="Villain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("birthday", models.CharField(max_length=16)),
                (
                    "demise",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("height", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name": "Villain",
                "verbose_name_plural": "Villains",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("main_actor", models.CharField(max_length=64)),
                ("director", models.CharField(max_length=64)),
                ("summary", models.TextField()),
                ("published", models.PositiveIntegerField()),
                (
                    "casts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.cast",  # noqa E501
                    ),
                ),
                (
                    "villains",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.villain",  # noqa E501
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
    ]
